app:
  name: my-app
  replicas: 2
  image:
    repository: nginx
    tag: "1.16"
  containerPort: 8080

db:
  name: my-db
  replicas: 1
  image:
    repository: postgres
    tag: "17"
  containerPort: 5432