app:
  name: my-app
  replicas: 2
  image:
    repository: my-app-image
    tag: "1.0.0"
  containerPort: 8080

db:
  name: my-db
  replicas: 1
  image:
    repository: my-db-image
    tag: "1.0.0"
  containerPort: 5432